
%el siguiente código grafica los controladores
figure(1)
subplot(2,2,1)
plot(control1.time, control1.signals.values,'r')
xlabel('Tiempo (min)') 
ylabel('Tasa de infusión de propofol') 
subplot(2,2,2)
plot(control2.time, control2.signals.values,'b')
xlabel('Tiempo (min)') 
ylabel('Tasa de infusión de propofol') 
subplot(2,2,3)
plot(control3.time, control3.signals.values,'c')
ylabel('Tasa de infusión de propofol') 
xlabel('Tiempo (min)') 
subplot(2,2,4)
plot(control4.time, control4.signals.values,'m')
xlabel('Tiempo (min)') 
ylabel('Tasa de infusión de propofol') 

%estas son las gráficas de la señal BIS de los pacientes
figure(2)
subplot(2,2,1)
plot(paciente1.time, paciente1.signals.values,'g')
xlabel('Tiempo (min)') 
ylabel('Indice BIS') 
subplot(2,2,2)
plot(paciente2.time, paciente2.signals.values,'b')
xlabel('Tiempo (min)') 
ylabel('Indice BIS') 
subplot(2,2,3)
plot(paciente3.time, paciente3.signals.values,'r')
ylabel('Indice BIS') 
xlabel('Tiempo (min)') 
subplot(2,2,4)
plot(paciente4.time, paciente4.signals.values,'m')
xlabel('Tiempo (min)') 
ylabel('Indice BIS') 
